### ISSUE TITLE
Restricting users with RLS Policy, not working

### ISSUE THREAD

**Issue by Hudson-AmalembaL** [dijonmusters/build-a-twitter-clone-with-the-next.js-app-router-and-supabase#5]
Hello, hope your doing well. I've been following along the tutorial. 
On this video, `07-restrict-access-to-authenticated-users-with-rls-policies`
Line by line i've replicated what you have but the tweets are only showed when the policy is for public, the moment i turn on `authenticated`, nothing shows.

i've even cloned this repo, pasted my supabase credentials, same problem.Even when i'm logged in.
Might it be because of the major update the has been made recently given this tutorial was made over a month ago??

Help would really come a long way.

**Comment by BenitoPFM** [comment]
Same problem here. How did you solve it?

**Comment by Hudson-AmalembaL** [comment]
> Same problem here. How did you solve it?

i just tried it very many times. to a point i left the tutorial and started learning from scratch line by line, from the supabase website. I figured the tutorial is only useful when you already have your own background of what is happening behind the curtains.

My point is my mistake was i was trying to hurry it up with no basics. Didn't work. Just take a minute.

**Comment by BenitoPFM** [comment]
OK, but the issue is still there. Something has changed as it works in the video. Whether or not it is recommended to have the basics of Supabase before doing this tutorial (honestly, I was just looking for a quick tutorial that would introduce it in a broader context, so I didn't feel the need to have the basics of Supabase).

**Comment by Hudson-AmalembaL** [comment]
yeah. that was me too.

**Comment by arjunsajeev** [comment]
@Hudson-AmalembaL @benipublic How was this resolved?

**Comment by Hudson-AmalembaL** [comment]
> @Hudson-AmalembaL @benipublic How was this resolved?

By simply learning the very basics of supabase first. From my opinion the tutorial assumes you have some little knowledge about supabase.

**Comment by arjunsajeev** [comment]
> > @Hudson-AmalembaL @benipublic How was this resolved?
> 
> 
> 
> By simply learning the very basics of supabase first. From my opinion the tutorial assumes you have some little knowledge about supabase.

It would be useful if you could post the solution for others following the thread.
