### ISSUE TITLE
CH12: can't recreate user by logging in

### ISSUE THREAD

**Issue by alcidenik0pol** [dijonmusters/build-a-twitter-clone-with-the-next.js-app-router-and-supabase#8]
hi,

in CH12, once I created the function, the trigger, and deleted my users (and tweets), I can't recreate any user by logging in.
when I click login, the cookie is created, but it stays on login page.

my function:
```
begin
  insert into public.profiles(id, name, username, avatar_url)
  values(
    new.id,
    new.raw_user_meta_data->>'name',
    new.raw_user_meta_data->>'user_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
```
i activated the corresponding trigger as well.

**Comment by nakzyu** [comment]
Because you dont have github nickname. check this isssue https://github.com/dijonmusters/build-a-twitter-clone-with-the-next.js-app-router-and-supabase/issues/4, fix is included.

**Comment by alcidenik0pol** [comment]
thanks, that did it!
